export const EventBackButtonPressed = 'back_button_pressed'
export const EventClipboardTextReceived = 'clipboard_text_received'
export const EventCustomMethodInvoked = 'custom_method_invoked'
export const EventInvoiceClosed = 'invoice_closed'
export const EventMainButtonPressed = 'main_button_pressed'
export const EventPhoneRequested = 'phone_requested'
export const EventPopupClosed = 'popup_closed'
export const EventReloadIframe = 'reload_iframe'
export const EventQrTextReceived = 'qr_text_received'
export const EventScanQrPopupClosed = 'scan_qr_popup_closed'
export const EventSetCustomStyle = 'set_custom_style'
export const EventSettingsButtonPressed = 'settings_button_pressed'
export const EventThemeChanged = 'theme_changed'
export const EventViewportChanged = 'viewport_changed'
export const EventWriteAccessRequested = 'write_access_requested'
export const EventSafeAreaChanged = 'safe_area_changed'
export const EventContentSafeAreaChanged = 'content_safe_area_changed'

export const EventPreparedMessageSent = 'prepared_message_sent'
export const EventPreparedMessageFailed = 'prepared_message_failed'
export const EventEmojiStatusSet = 'emoji_status_set'
export const EventEmojiStatusFailed = 'emoji_status_failed'
export const EventEmojiStatusAccessRequested = 'emoji_status_access_requested'
export const EventFileDownloadRequested = 'file_download_requested'

export const EventAccelerometerChanged = 'accelerometer_changed'
export const EventAccelerometerFailed = 'accelerometer_failed'
export const EventAccelerometerStarted = 'accelerometer_started'
export const EventAccelerometerStopped = 'accelerometer_stopped'

export const EventBiometryAuthRequested = 'biometry_auth_requested'
export const EventBiometryInfoReceived = 'biometry_info_received'
export const EventBiometryTokenUpdated = 'biometry_token_updated'

export const EventDeviceOrientationChanged = 'device_orientation_changed'
export const EventDeviceOrientationFailed = 'device_orientation_failed'
export const EventDeviceOrientationStarted = 'device_orientation_started'
export const EventDeviceOrientationStopped = 'device_orientation_stopped'

export const EventFullscreenChanged = 'fullscreen_changed'
export const EventFullscreenFailed = 'fullscreen_failed'

export const EventGyroscopeChanged = 'gyroscope_changed'
export const EventGyroscopeFailed = 'gyroscope_failed'
export const EventGyroscopeStarted = 'gyroscope_started'
export const EventGyroscopeStopped = 'gyroscope_stopped'

export const EventHomeScreenAdded = 'home_screen_added'
export const EventHomeScreenChecked = 'home_screen_checked'

export const EventLocationChecked = 'location_checked'
export const EventLocationRequested = 'location_requested'

export const EventSecondaryButtonPressed = 'secondary_button_pressed'

export const EventDeviceStorageKeySaved = 'device_storage_key_saved'
export const EventDeviceStorageKeyReceived = 'device_storage_key_received'
export const EventDeviceStorageCleared = 'device_storage_cleared'
export const EventDeviceStorageFailed = 'device_storage_failed'

export const EventSecureStorageKeySaved = 'secure_storage_key_saved'
export const EventSecureStorageKeyReceived = 'secure_storage_key_received'
export const EventSecureStorageKeyRestored = 'secure_storage_key_restored'
export const EventSecureStorageCleared = 'secure_storage_cleared'
export const EventSecureStorageFailed = 'secure_storage_failed'

export const EventRequestedChatSent = 'requested_chat_sent'
export const EventRequestedChatFailed = 'requested_chat_failed'

export const EventVisibilityChanged = 'visibility_changed'
