import sender from './sender'
import {
	bridgeClose,
	bridgeCloseScanQrPopup,
	bridgeDataSend,
	bridgeExpand,
	bridgeIframeReady,
	bridgeIframeWillReload,
	bridgeInvokeCustomMethod,
	bridgeOpenScanQrPopup,
	bridgeReadTextFromClipboard,
	bridgeRequestPhone,
	bridgeOpenInvoice,
	bridgeOpenLink,
	bridgeOpenPopup,
	bridgeOpenTgLink,
	bridgeReady,
	bridgeRequestTheme,
	bridgeRequestWriteAccess,
	bridgeRequestViewport,
	bridgeSetBackgroundColor,
	bridgeSetHeaderColor,
	bridgeSetBottomBarColor,
	bridgeSetupBackButton,
	bridgeSetupClosingBehavior,
	bridgeSetupMainButton,
	bridgeSetupSecondaryButton,
	bridgeSetupSettingsButton,
	bridgeSwitchInlineQuery,
	bridgeTriggerHapticFeedback,
	bridgeSetupSwipeBehavior,
	bridgeCheckLocation,
	bridgeOpenLocationSettings,
	bridgeRequestLocation,
	bridgeStartAccelerometer,
	bridgeStopAccelerometer,
	bridgeStartDeviceOrientation,
	bridgeStopDeviceOrientation,
	bridgeStartGyroscope,
	bridgeStopGyroscope,
	bridgeHideKeyboard,
	bridgeRequestChat,
	bridgeShareToStory,
	bridgeRequestSafeAreaInset,
	bridgeRequestContentSafeAreaInset,
	bridgeSetupFullScreen,
	bridgeSetupOrientation,
	bridgeAddToHomeScreen,
	bridgeCheckHomeScreen,
	bridgeRequestEmojiStatus,
	bridgeSetEmojiStatus,
	bridgeShareMessage,
	bridgeDownloadFile,
	bridgeBiometricManager,
	bridgeDeviceStorage,
	bridgeSecureStorage,
} from './solid'
import {
	MethodClose,
	MethodCloseScanQrPopup,
	MethodDataSend,
	MethodExpand,
	MethodIframeReady,
	MethodIframeWillReload,
	MethodInvokeCustomMethod,
	MethodOpenInvoice,
	MethodOpenLink,
	MethodOpenPopup,
	MethodOpenScanQrPopup,
	MethodOpenTgLink,
	MethodReadTextFromClipboard,
	MethodReady,
	MethodRequestPhone,
	MethodRequestTheme,
	MethodRequestViewport,
	MethodRequestWriteAccess,
	MethodSetBackgroundColor,
	MethodSetBottomBarColor,
	MethodSetHeaderColor,
	MethodSetupBackButton,
	MethodSetupClosingBehavior,
	MethodSetupMainButton,
	MethodSetupSecondaryButton,
	MethodSetupSettingsButton,
	MethodSetupSwipeBehavior,
	MethodCheckLocation,
	MethodOpenLocationSettings,
	MethodRequestLocation,
	MethodStartAccelerometer,
	MethodStopAccelerometer,
	MethodStartDeviceOrientation,
	MethodStopDeviceOrientation,
	MethodStartGyroscope,
	MethodStopGyroscope,
	MethodHideKeyboard,
	MethodRequestChat,
	MethodShareToStory,
	MethodRequestSafeArea,
	MethodRequestContentSafeArea,
	MethodRequestFullscreen,
	MethodExitFullscreen,
	MethodToggleOrientationLock,
	MethodAddToHomeScreen,
	MethodCheckHomeScreen,
	MethodSendPreparedMessage,
	MethodSetEmojiStatus,
	MethodRequestEmojiStatusAccess,
	MethodRequestFileDownload,
	MethodBiometryGetInfo,
	MethodBiometryOpenSettings,
	MethodBiometryRequestAccess,
	MethodBiometryRequestAuth,
	MethodBiometryUpdateToken,
	MethodDeviceStorageSaveKey,
	MethodDeviceStorageGetKey,
	MethodDeviceStorageClear,
	MethodSecureStorageSaveKey,
	MethodSecureStorageGetKey,
	MethodSecureStorageRestoreKey,
	MethodSecureStorageClear,
	MethodSwitchInlineQuery,
	MethodTriggerHapticFeedback,
	type SenderData,
} from './types/methods'

type Entry = (data?: unknown) => unknown

const lazy = (callback: () => (...args: never[]) => unknown): Entry =>
	data => callback()(data as never)

const entries = {
	[MethodInvokeCustomMethod]: lazy(() => bridgeInvokeCustomMethod),
	[MethodOpenScanQrPopup]: lazy(() => bridgeOpenScanQrPopup),
	[MethodReadTextFromClipboard]: lazy(() => bridgeReadTextFromClipboard),
	[MethodRequestPhone]: lazy(() => bridgeRequestPhone),
	[MethodClose]: lazy(() => bridgeClose),
	[MethodCloseScanQrPopup]: lazy(() => bridgeCloseScanQrPopup),
	[MethodDataSend]: lazy(() => bridgeDataSend),
	[MethodExpand]: lazy(() => bridgeExpand),
	[MethodIframeReady]: lazy(() => bridgeIframeReady),
	[MethodIframeWillReload]: lazy(() => bridgeIframeWillReload),
	[MethodOpenInvoice]: lazy(() => bridgeOpenInvoice),
	[MethodOpenLink]: lazy(() => bridgeOpenLink),
	[MethodOpenPopup]: lazy(() => bridgeOpenPopup),
	[MethodOpenTgLink]: lazy(() => bridgeOpenTgLink),
	[MethodReady]: lazy(() => bridgeReady),
	[MethodRequestTheme]: lazy(() => bridgeRequestTheme),
	[MethodRequestViewport]: lazy(() => bridgeRequestViewport),
	[MethodRequestWriteAccess]: lazy(() => bridgeRequestWriteAccess),
	[MethodSetBackgroundColor]: lazy(() => bridgeSetBackgroundColor),
	[MethodSetHeaderColor]: lazy(() => bridgeSetHeaderColor),
	[MethodSetBottomBarColor]: lazy(() => bridgeSetBottomBarColor),
	[MethodSetupBackButton]: lazy(() => bridgeSetupBackButton),
	[MethodSetupClosingBehavior]: lazy(() => bridgeSetupClosingBehavior),
	[MethodSetupMainButton]: lazy(() => bridgeSetupMainButton),
	[MethodSetupSecondaryButton]: lazy(() => bridgeSetupSecondaryButton),
	[MethodSetupSettingsButton]: lazy(() => bridgeSetupSettingsButton),
	[MethodSwitchInlineQuery]: lazy(() => bridgeSwitchInlineQuery),
	[MethodTriggerHapticFeedback]: lazy(() => bridgeTriggerHapticFeedback),
	[MethodSetupSwipeBehavior]: lazy(() => bridgeSetupSwipeBehavior),
	[MethodCheckLocation]: lazy(() => bridgeCheckLocation),
	[MethodOpenLocationSettings]: lazy(() => bridgeOpenLocationSettings),
	[MethodRequestLocation]: lazy(() => bridgeRequestLocation),
	[MethodStartAccelerometer]: lazy(() => bridgeStartAccelerometer),
	[MethodStopAccelerometer]: lazy(() => bridgeStopAccelerometer),
	[MethodStartDeviceOrientation]: lazy(() => bridgeStartDeviceOrientation),
	[MethodStopDeviceOrientation]: lazy(() => bridgeStopDeviceOrientation),
	[MethodStartGyroscope]: lazy(() => bridgeStartGyroscope),
	[MethodStopGyroscope]: lazy(() => bridgeStopGyroscope),
	[MethodHideKeyboard]: lazy(() => bridgeHideKeyboard),
	[MethodRequestChat]: lazy(() => bridgeRequestChat),
	[MethodShareToStory]: lazy(() => bridgeShareToStory),
	[MethodRequestSafeArea]: lazy(() => bridgeRequestSafeAreaInset),
	[MethodRequestContentSafeArea]: lazy(() => bridgeRequestContentSafeAreaInset),
	[MethodRequestFullscreen]: () => bridgeSetupFullScreen({ is_full: true }),
	[MethodExitFullscreen]: () => bridgeSetupFullScreen({ is_full: false }),
	[MethodToggleOrientationLock]: lazy(() => bridgeSetupOrientation),
	[MethodAddToHomeScreen]: lazy(() => bridgeAddToHomeScreen),
	[MethodCheckHomeScreen]: lazy(() => bridgeCheckHomeScreen),
	[MethodSendPreparedMessage]: lazy(() => bridgeShareMessage),
	[MethodSetEmojiStatus]: lazy(() => bridgeSetEmojiStatus),
	[MethodRequestEmojiStatusAccess]: lazy(() => bridgeRequestEmojiStatus),
	[MethodRequestFileDownload]: lazy(() => bridgeDownloadFile),
	[MethodBiometryGetInfo]: () => bridgeBiometricManager.init(),
	[MethodBiometryOpenSettings]: lazy(() => bridgeBiometricManager.openSettings),
	[MethodBiometryRequestAccess]: lazy(() => bridgeBiometricManager.requestAccess),
	[MethodBiometryRequestAuth]: lazy(() => bridgeBiometricManager.authenticate),
	[MethodBiometryUpdateToken]: lazy(() => bridgeBiometricManager.updateToken),
	[MethodDeviceStorageSaveKey]: lazy(() => bridgeDeviceStorage.setItem),
	[MethodDeviceStorageGetKey]: lazy(() => bridgeDeviceStorage.getItem),
	[MethodDeviceStorageClear]: lazy(() => bridgeDeviceStorage.clear),
	[MethodSecureStorageSaveKey]: lazy(() => bridgeSecureStorage.setItem),
	[MethodSecureStorageGetKey]: lazy(() => bridgeSecureStorage.getItem),
	[MethodSecureStorageRestoreKey]: lazy(() => bridgeSecureStorage.restoreItem),
	[MethodSecureStorageClear]: lazy(() => bridgeSecureStorage.clear),
}

export const send = async <E extends keyof SenderData>(
	name: E,
	data?: SenderData[E]
): Promise<unknown> => {
	const callback = entries[name as keyof typeof entries] as
		| ((data?: SenderData[E]) => unknown)
		| undefined
	if (callback) {
		return await callback(data)
	}
	return await sender(name, data)
}

export default send
